// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://goqmhnpktoebfltpuktf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvcW1obnBrdG9lYmZsdHB1a3RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MDMzNTMsImV4cCI6MjA3MDM3OTM1M30.rIFBWQK7oRvCccii_UrLEejYEyt5u8S8I2d5ATG8BxE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});